apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-search
  labels:
    app: server-search
spec:
  selector:
    matchLabels:
      app: server-search
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server-search
    spec:
      containers:
      - name: server-search
        image: keremkaragulle/server-search:1.0
        env:
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_DATABASE_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: servers-configmap
              key: MYSQL_USER            
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 80
          name: server-search
      restartPolicy: Always