kind: Service
apiVersion: v1
metadata:
  name:  search-service
spec:
  selector:
    app: server-search
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP