kind: Service
apiVersion: v1
metadata:
  name:  cdu-service
spec:
  selector:
    app: server-cdu
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP